repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: remove-crlf
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
  - repo: https://github.com/google/yapf.git
    rev: v0.43.0
    hooks:
      - id: yapf
        files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=10000 ]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: copyright_checker
        name: copyright_checker
        entry: python ./tools/codestyle/copyright.hook
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|proto|py)$
        exclude: (?!.*third_party)^.*$ | (?!.*book)^.*$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [ "--skip", "*.hook", "--ignore-words-list", "ans,nd,Bu,astroid,hart" ]
